services:
  app:
    build: .
    container_name: gold-monkey-app
    env_file: .env
    ports:
      - "8501:8501"
    command: python -m streamlit run main.py

  saltybot:
    build: .
    container_name: saltybot-server
    env_file: .env
    command: python mcp_servers/saltybot_server.py
    depends_on:
      - app

  roku:
    build: .
    container_name: roku-server
    env_file: .env
    command: python mcp_servers/roku_server.py
    depends_on:
      - app

  spotify:
    build: .
    container_name: spotify-server
    env_file: .env
    command: python mcp_servers/spotify_server.py
    depends_on:
      - app

  tplink:
    build: .
    container_name: tplink-server
    env_file: .env
    command: python mcp_servers/tplink_server.py
    depends_on:
      - app

  rag:
    build: .
    container_name: rag-server
    env_file: .env
    command: python mcp_servers/rag_server.py
    depends_on:
      - app

  voice:
    build: .
    container_name: voice-server
    env_file: .env
    command: python mcp_servers/voice_server.py
    depends_on:
      - app

  # Optional: add volumes for persistent data
  #    volumes:
  #      - ./data:/app/data 